version: "3.7"
services:
   postgres:
    restart: always
    image: postgres:12
    container_name: teach-carrot-hub-postgres
    volumes:
      - teach-carrot-hub_pdata_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  teach-carrot-hub_pdata_volume:
    driver: local

networks:
  teach-carrot-hub:
    name: teach-carrot-hub-network
    driver: bridge
